### ISSUE TITLE
Jinja2 for Previous/Next Page

### ISSUE THREAD

**Issue by dirtycajunrice** [Skyost/SkyDocs#7]
You have it grouped with if either button exists, show both buttons. I believe this should be broken out into separate if statements. Why show a button that is not usable?

e.g:

```
{% if page.hasPreviousPage() or page.hasNextPage() %}
    <div class="paginator clearfix no-print">
        {% if page.hasPreviousPage() %}
        <a class="btn btn-secondary float-left{% if page.hasPreviousPage() %}" href="{{ page.getPreviousPage() }}"{% else %} disabled" aria-disabled="true" href="#"{% endif %} role="button"><i class="fa fa-arrow-left" aria-hidden="true"></i></a>
        {% endif %}
        {% if page.hasNextPage() %}
        <a class="btn btn-secondary float-right{% if page.hasNextPage() %}" href="{{ page.getNextPage() }}"{% else %} disabled" aria-disabled="true" href="#"{% endif %} role="button"><i class="fa fa-arrow-right" aria-hidden="true"></i></a>
        {% endif %}
    </div>
{% endif %}
```

**Comment by Skyost** [comment]
Hey,

If you take a look at [the recent commits](https://github.com/Skyost/SkyDocs/blob/master/src/main/resources/default_theme/page.html#L20), I've already fixed this one :wink:

**Comment by dirtycajunrice** [comment]
It’s not working how you think it is. Still shows both buttons

**Comment by Skyost** [comment]
Yes but it shows a disabled button if no previous page is available (same for next pages).

![Screenshot](https://i.imgur.com/evCJWel.png)

**Comment by dirtycajunrice** [comment]
Guess its a difference in opinion for design decision. You are the creator :) ill close it out

**Comment by Skyost** [comment]
Yeah, but feel free to customize it in your theme directory :wink:
